### ISSUE TITLE
Include display, clear and control functionality in library

### ISSUE THREAD

**Issue by moritz89** [Jomelo/LCDMenuLib2#58]
Currently the clear, display and control functions have to be included in addition to the menu library. To add this functionality, it has to be copy and pasted for each project with no central overview (except for the examples).

It would be very user friendly and aid in staying up to date if this functionality would be included in the core library and be enabled on a project by project basis with defines. Is there a plan to transition the code base in this direction?

**Comment by Jomelo** [comment]
In early versions i have include the display and control part completly in the library. The problem was the many differnt display librarys and configuration methods. So i deceide a few years ago to use callback function for this problem.

I will not say that is the best way but it works well because everyone can edit this function for every special project. 

I can understand your suggestion and i'm open to new implementation ways i haven't thought about yet. Can you create a samll example of how you imagine that ?
